FROM arturopala/scala:2.11.7
RUN apt-get update && \
    apt-get install -y git && \
    apt-get install -y texlive
RUN apt-get update && \
    apt-get install -y dvipng texlive-bibtex-extra texlive-pictures texlive-science
 
